### ISSUE TITLE
Workshop and other images for the gallery

### ISSUE THREAD

**Issue by mjcollin** [dsiufl/www.dsiufl.org-2016#13]
Collect at least 5 or many images for the gallery page. Workshop images can get monotonous if it's always the same classroom. Are there other fun images?

**Comment by xiaoyaya** [comment]
Uploaded 12 photos in the gallery. 1900 * 1263, about 500 kb per photo.
Tested the latency, which is acceptable. Keep this standard or reduce it a little?
650 * 350 is too small to be blur when viewing it on the big screen.

**Comment by xiaoyaya** [comment]
If the .md file mentioned the photo, then workshop.html would deal with it. Otherwise, there won't be an photo in the post.

I was thinking this photo could be used for installation or output result such as data visualization purpose.

**Comment by mjcollin** [comment]
Resolved
