### ISSUE TITLE
Front carousel images

### ISSUE THREAD

**Issue by mjcollin** [dsiufl/www.dsiufl.org-2016#14]
3 good images for the carousel?

**Comment by xiaoyaya** [comment]
Do we resize the carousel a little?

**Comment by mjcollin** [comment]
Are you are thinking smaller or larger? It could go a little taller but I like the ability to see the top of the text on the page. I'm old-fashioned though and I don't like web sites like this: http://billbyronwines.com/

I want to read what you have to say without having to scroll around for it.

I originally opened this ticket to confirm that the three images we have are the ones we want to show.

**Comment by mjcollin** [comment]
Resolved
