### ISSUE TITLE
Make design more center-y

### ISSUE THREAD

**Issue by mjcollin** [dsiufl/www.dsiufl.org-2016#2]
The main content column is a little too wide. Slim it by maybe 10% on a side? This would look better when there's lots of content but some small elements will still look squashed left like the footer. Center the text in the footer?

**Comment by mjcollin** [comment]
Center calendar on the calendar page

**Comment by xiaoyaya** [comment]
Calendar centered.

Main content? Don't quite understand. The section is restraint by row section.

**Comment by mjcollin** [comment]
As an example, this site: http://alanwsmith.com/jekyll-liquid-date-formatting-examples has the content column set to about 50% of my monitor width. As a result the content looks "centered" without the text being aligned center. It means your eyes have to scan across less as you read. It's the same reason newspapers do columns and publications do 2-column layouts. It looks nicer to most people and is easier to read.

I suggest making the width of the main content column of all pages to be about 800px or something that scaled to about 60% of the monitor width until the monitor width is less than 800px.

The footer text can be aligned center regardless of the column width.

**Comment by xiaoyaya** [comment]
Centered the body to occupy 10 columns with 1 column offset to the left.
Didn't touch the header part because the color inconsistency.
Centered the footer.

How does this look?

**Comment by mjcollin** [comment]
I think it looks much better. I tried it on several screen sizes and it easy to read on them all.
