### ISSUE TITLE
Add events to Google calendar

### ISSUE THREAD

**Issue by mjcollin** [dsiufl/www.dsiufl.org-2016#5]
The calendar is currently empty. Need to add events and add managing the calendar to the tasks of the social director so it stays current. What Google account is the calendar under? Who can access it?

**Comment by xiaoyaya** [comment]
The calendar uses "dsiufl@gmail.com" account. Whoever has access to this account should be able to add events on 

Any event under "Event" tag would be public and shown on the calendar.html.

Instruction updated on README.md
