### ISSUE TITLE
Rename Portfolio to Gallery

### ISSUE THREAD

**Issue by mjcollin** [dsiufl/www.dsiufl.org-2016#7]
Gallery a better name? Pictures should have title under them like "Python workshop, March 2016?". If so, how should we do this: .md file collections? If it is a collection, need to do automatic paging.

**Comment by xiaoyaya** [comment]
Solved by creating collection called "gallery" and write some code on modern_business.css.
Once put cursor on picture, the title and date should be displayed.

**Comment by mjcollin** [comment]
I pushed a commit that made the gallery a little more easy to maintain.
