### ISSUE TITLE
Purpose of Workshops section

### ISSUE THREAD

**Issue by mjcollin** [dsiufl/www.dsiufl.org-2016#8]
Initially I was thinking that the workshops was going to be an upcoming events type thing where each workshop hosted would get a new page added. If that was going to be the case, then I was wondering where to put "permanent" things like how to install Anaconda.

Now I think that it's intention was to have a page describing the workshop and the calendar is the upcoming events type place. So there would be one "Python 0" page, one "Stats 0" page, etc. Perhaps as we changed the workshops over time we could have "Python 0 - 2016 version" or something. Maybe we just edit the pages and rely on git to keep version histories.

There still needs to be a common place to talk about setting up software though. Maybe we could agree that Python 0 documents the installation of Anaconda and Python I and Visualization etc all link back to Python 0 with "Please perform the setup steps from Python 0".

**Comment by xiaoyaya** [comment]
I was thinking that workshops.html is used for a collections of posts advising members to get started. Yes, so there would be one "Python 0" page, which describes how to install anaconda, and with a link to the corresponding GitHub repository. So whenever there is a "Python 0" workshop, the content manager can create a Facebook event and a Google calendar event, both referencing this "Python 0" post address. 
If someone who is totally new to UFDSI, they can still have an idea about our various types of workshops by simply scrolling down the workshops.html webpage.

**Comment by mjcollin** [comment]
Sounds like we agree on the purpose. I re-worked the workshops a little to make the setup more intuitive. If you have additional changes or tweaks, feel free to make them. I'm going to close this ticket since this topic seems settled.
